### ISSUE TITLE
wu-plus-image 多图预览

### ISSUE THREAD

**Issue by leonhu0710** [wu-component/web-component-plus#78]
请问 image  图片支持多图切换吗？master 按 文档示例配置了 preview-src-list ，并未生效

**Comment by canyuegongzi** [comment]
> 

支持的，可以提供下示例代码吗？


```
<wu-plus-image preview-src-list="['https://cube.elemecdn.com/6/94/4d3ea53c084bad6931a56d5158a48jpeg.jpeg']" style="width: 300px; height: 200px" src="https://cube.elemecdn.com/6/94/4d3ea53c084bad6931a56d5158a48jpeg.jpeg">
            <div slot="placeholder" class="image-slot" style="display: flex;justify-content: center;align-items: center; width: 100%;height: 100%;background: #f5f7fa;color: #909399;">
                加载中<span class="dot">...</span>
            </div>
        </wu-plus-image>
```

**Comment by leonhu0710** [comment]
<wu-plus-image src="https://dgss0.bdstatic.com/5bVWsj_p_tVS5dKfpU_Y_D3/res/r/image/2017-09-27/297f5edb1e984613083a2d3cc0c5bb36.png" preview-src-list="['https://dgss0.bdstatic.com/5bVWsj_p_tVS5dKfpU_Y_D3/res/r/image/2017-09-27/297f5edb1e984613083a2d3cc0c5bb36.png', 
      'https://cube.elemecdn.com/6/94/4d3ea53c084bad6931a56d5158a48jpeg.jpeg']">
        <div slot="error" class="image-slot-error" style="display: flex;justify-content: center;align-items: center; width: 100%;height: 100%;background: transparent;color: #909399;">加载失败</div>
      </wu-plus-image>  
配置 多个 地址， 切换时候没有反应

**Comment by leonhu0710** [comment]
我我的问题，我定位到了，html 字串 把数组转换了，导致切换不生效，叨扰作者了。  <wu-plus-image src="http://localhost:8082/flow/picture/企业微信截图_2023020814252420230208142925853.png"
       preview-src-list="http://localhost:8082/flow/picture/企业微信截图_2023020814252420230208142925853.png">
        <div slot="error" class="image-slot-error" style="display: flex;justify-content: center;align-items: center; width: 100%;height: 100%;background: transparent;color: #909399;">加载失败</div>
       </wu-plus-image>

**Comment by leonhu0710** [comment]
![企业微信截图_16762701842831](https://user-images.githubusercontent.com/16177248/218387854-e11d1daf-f868-4d12-a3c7-782fddfd7a03.png)

**Comment by leonhu0710** [comment]
> ![企业微信截图_16762701842831](https://user-images.githubusercontent.com/16177248/218387854-e11d1daf-f868-4d12-a3c7-782fddfd7a03.png)

不能直接传递数组，要转换成数组字符串

**Comment by canyuegongzi** [comment]
> 把数组转换了

是的，webcomponent 实际就是自定义的html 标签，只支持字符串属性的
