### ISSUE TITLE
wu-plus-image

### ISSUE THREAD

**Issue by leonhu0710** [wu-component/web-component-plus#79]
通过GET接口方式获取的图片,无法预览

**Comment by canyuegongzi** [comment]
> 
get 接口方式？示例代码提供下

**Comment by leonhu0710** [comment]
不好意思，我换成静态资源方式 预览有问题，换成百度在线图片没问题，应该和 wu-plus-image 无关，需要配置绝对地址，不能用相对地址吗?

**Comment by canyuegongzi** [comment]
> 不好意思，我换成静态资源方式 预览有问题，换成百度在线图片没问题，应该和 wu-plus-image 无关，需要配置绝对地址，不能用相对地址吗?

目前是，后续可以考虑支持
